webapp/filter/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, PasswordField
from wtforms.validators import DataRequired


class SearchForm(FlaskForm):
    token = PasswordField('Персональный токен', validators=[DataRequired()],
                          render_kw={"class": "form-control"})
    filter = StringField('ID фильтра', validators=[DataRequired()],
                         render_kw={"class": "form-control"})
    download = SubmitField('Скачать', render_kw={"class": "btn btn-primary"})

webapp/__init__.py
from flask import Flask
import logging

from webapp.filter.views import blueprint as search_blueprint

# Конфигурация логов
logging.basicConfig(filename='project.log',
                    format='%(asctime)s %(message)s',
                    datefmt='%m/%d/%Y %I:%M:%S %p',
                    level=logging.INFO,
                    encoding='utf-8')


def create_app():
    app = Flask(__name__)
    app.config.from_pyfile('config.py')

    app.register_blueprint(search_blueprint)

    logging.info("Сервис запустился")
    return app

webapp/filter/views.py
from flask import (Blueprint, render_template, flash,
                   redirect, url_for, send_file)


from webapp.status_jira import status_jira
from webapp.filter.forms import SearchForm
from webapp.issues_filter import process_general_CSV_from_filter

# Родительский URL
blueprint = Blueprint('search', __name__)


@blueprint.route('/')
def index():
    title = "Микросервис отчетов Jira"
    status = status_jira()
    # Создание экземпляра класса
    search_form = SearchForm()
    return render_template('base.html', page_title=title,
                           status=status, form=search_form)


@blueprint.route('/process-search', methods=['POST'])
def process_search():
    form = SearchForm()

    if form.validate_on_submit():
        process = process_general_CSV_from_filter(filter=form.filter.data,
                                                  jira_api_key=form.token.data)
        if process['bool']:
            flash(process['text'])
            return send_file(f'issues_from_filter_{form.filter.data}.csv')
        else:
            flash(process['error'])
    return redirect(url_for('search.index'))

webapp/templates/base.html
<!doctype html>
<html lang="ru">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>{{ page_title }}</title>
  </head>
  <body>
    <div class="container">
        <h1>{{ page_title }}</h1>
          {% include 'jira.html' %}
          {% if status['bool'] %}
            {% include 'search.html' %}
          {% endif %}
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

webapp/templates/index.html
<!doctype html>
<html lang="ru">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>{{ page_title }}</title>
  </head>
  <body>
    <div class="container">
    <h1>Cтатус Jira: {{status}}</h1>
    <div class="row">
      <div class="col-8">
        <h2>Поля</h2>
        {% for field in feilds_list %}
        <p>{{ field.field_id }} : {{ field.field_name }}</p>
        <hr />
        {% endfor %}
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

webapp/templates/jira.html
<div class="row">
    <div class="col-12">
        <div class="alert alert-warning" role="alert">
            {{ status['text'] }}<br>
        </div>
    </div>
</div>

webapp/templates/search.html
<div class="row">
  <div class="col-12">
    {% with messages = get_flashed_messages() %}
      {% if messages %}
      <div class="alert alert-danger" role="alert">
          {{messages[0]}}<br>
      </div>
      {% endif %}
    {% endwith %}
      <form action="{{ url_for('search.process_search') }}" method="post">
        {{ form.hidden_tag() }}
        <div class="form-group">
          {{ form.token.label }}
          {{ form.token() }}
        </div>
        <div class="form-group">
          {{ form.filter.label }}
          {{ form.filter() }}
        </div>
        {{ form.download }}
      </from>
  </div>